[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "vue"
auto-format = true
language-servers = [
  { name = "vuels", except-features = ["inlay-hints"] },
  "typescript-language-server"
]

[[language]]
name = "rust"
auto-format = true

[language-server.vuels]
command = "vue-language-server"
args = ["--stdio"]

[language-server.vuels.config]
typescript = { tsdk = "/Users/ushironoko/.bun/install/global/node_modules/typescript/lib" }

[language-server.typescript-language-server.config]
preferences.includeInlayParameterNameHints = "all"
preferences.includeInlayParameterNameHintsWhenArgumentMatchesName = false
preferences.includeInlayFunctionParameterTypeHints = true
preferences.includeInlayVariableTypeHints = true
preferences.includeInlayVariableTypeHintsWhenTypeMatchesName = false
preferences.includeInlayPropertyDeclarationTypeHints = true
preferences.includeInlayFunctionLikeReturnTypeHints = true
preferences.includeInlayEnumMemberValueHints = true

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/Users/ushironoko/.bun/install/global/node_modules/@vue/typescript-plugin"
languages = ["vue"]
