prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
    - key: g
      name: lazygit
      command: cd {{.RepoPath}} && lazygit
  prs:
    - key: d
      name: review (octorus)
      command: "or --repo {{.RepoName}} --pr {{.PrNumber}}"
    - key: D
      name: diff (no lock)
      command: "/Users/ushironoko/.local/bin/gh-diff-no-lock {{.RepoName}} {{.PrNumber}}"
    - key: M
      name: admin merge
      command: "gh pr merge {{.PrNumber}} -R {{.RepoName}} --admin --squash --delete-branch"
repoPaths:
  ushironoko/docsho: /Users/ushironoko/ghq/github.com/ushironoko/docsho
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: delta --paging=always --line-numbers
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
