[tools]
neovim = "latest"
helix = "latest"
node = "24.6.0"
starship = "latest"
ni = "23.2.0"
pnpm = "latest"
rust = "latest"
uv = "latest"
bun = "latest"
jq = "latest"
deno = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
"ubi:d-kuro/gwq" = "latest"
lazygit = "latest"
delta = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
